
development:
  adapter: postgresql
  encoding: unicode
  database: nerdpower_development
  pool: 5
  username: nerdpower
  password:


test:
  adapter: postgresql
  encoding: unicode
  database: nerdpower_test
  pool: 5
  username: nerdpower
  password:

